services:
  - type: web
    name: hidden-scan
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: "Hidden Scan"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_TIMEZONE
        value: Europe/Paris
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: hidden-scan-db
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: hidden-scan-db
          property: connectionString

databases:
  - name: hidden-scan-db
    databaseName: hidden_scan
    user: hidden_scan_user
    plan: free
    region: frankfurt
    postgresMajorVersion: "16"
